In [1]:
import numpy as np
import math

In [24]:
# randint(low, high=None, size=None, dtype='l')
x = np.random.randint(1,5,10)
x

array([4, 3, 1, 3, 3, 4, 4, 3, 3, 4])

In [22]:
# arange([start,] stop[, step,], dtype=None)
y = np.arange(4,8)
y

array([4, 5, 6, 7])

In [62]:
# np.linspace(
#     ['start', 'stop', 'num=50', 'endpoint=True', 'retstep=False', 'dtype=None', 'axis=0'],
# )
z = np.linspace(1,9,10,axis=0)
z

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

In [65]:
a = np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [68]:
a[3:,1:]

array([[10, 11],
       [13, 14]])

In [69]:
a.ndim

2

In [71]:
a.dtype.name

'int32'

In [72]:
a.itemsize

4

In [74]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [81]:
# zeros(shape, dtype=float, order='C')
d = np.zeros((3,3),dtype=np.float64,order='C')
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [84]:
# np.ones(shape, dtype=None, order='C')
e = np.ones((3,3),dtype=np.int32)
e

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [89]:
# np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
f = np.eye(3,3,0,dtype=np.int,order='C')
f

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [92]:
g=np.sin(z)
g

array([ 0.84147098,  0.94983371,  0.35584199, -0.50127705, -0.98772683,
       -0.7438021 ,  0.05012701,  0.80698971,  0.96712395,  0.41211849])

In [5]:
np.random.rand(3,2,2)

array([[[0.3303137 , 0.79761133],
        [0.96413852, 0.71373289]],

       [[0.04096602, 0.96692358],
        [0.51145409, 0.12501965]],

       [[0.42991679, 0.81763902],
        [0.87713578, 0.63237286]]])