In [2]:
import numpy as np

In [8]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [9]:
a[2]

8

In [10]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [20]:
a[:6:2] =-1000

In [21]:
a

array([-1000,     1, -1000,    27, -1000,   125, -1000,   343, -1000,
         729], dtype=int32)

In [22]:
a[::-1]

array([  729, -1000,   343, -1000,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [23]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [24]:
b[2,3]

23

In [29]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [34]:
b[-1]

array([40, 41, 42, 43])

In [40]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
print(c)
c.shape                                # same as c[:,:,2]

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]


(2, 2, 3)

In [38]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])