1) How to create a 1D array?

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.random.rand(3)
c = np.random.randint(1,3,3)
d = np.arange(1,4,1)
e = np.linspace(1,3,3)
list = [a,b,c,d,e]
for x in list:
    print(x, 'datatype:',x.dtype)

[1 2 3] datatype: int64
[0.53640154 0.21594182 0.25338609] datatype: float64
[1 2 1] datatype: int64
[1 2 3] datatype: int64
[1. 2. 3.] datatype: float64


2) How to create a boolean array?

In [4]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3) How to extract items that satisfy a given condition from 1D array?
   
   Extract all odd numbers from arr
   
   INPUT arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
   
   OUTPUT #> array([1, 3, 5, 7, 9])

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

4) How to replace items that satisfy a condition with another value in numpy array?

 Replace all odd numbers in arr with -1
 
 Input arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
 Output #>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])


In [15]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[1::2] = -1

In [16]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])