In [1]:
import numpy as np

In [4]:
print(np.__version__)
np.show_config()

1.14.3
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/sahilg/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sahilg/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/sahilg/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sahilg/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/sahilg/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sahilg/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/sahilg/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/sahilg/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/sahilg/anaconda3/lib']

In [5]:
z = np.zeros(10)

In [6]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
x = np.arange(10,50,2)
print(x)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [16]:
x[::-1]

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

In [19]:
# Create a 3x3 matrix with values ranging from 0 to 8
y = np.arange(0,9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
# Find indices of non-zero elements from [1,2,0,0,4,0] 
a = [1,2,0,0,4,0]
print(np.nonzero(a))

(array([0, 1, 4]),)


In [23]:
# Create a 3x3 identity matrix
b = np.eye(3)
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [27]:
# Create a 3x3x3 array with random values
c = np.random.random((3,3,3))
print(c)

[[[0.18597802 0.6946638  0.18151168]
  [0.7171415  0.05249069 0.18829669]
  [0.27943004 0.73737881 0.72564487]]

 [[0.35904597 0.00425422 0.14292496]
  [0.57783745 0.20136773 0.328277  ]
  [0.5455238  0.5404998  0.45183636]]

 [[0.51408039 0.18138198 0.24109997]
  [0.66692296 0.82902917 0.81057191]
  [0.54060807 0.21733395 0.1919736 ]]]


In [29]:
# Create a 10x10 array with random values and find the minimum and maximum values
d = np.random.random((10,10))
print(d,d.max(),d.min())

[[0.46117314 0.89702061 0.7797787  0.89795982 0.12366196 0.36643292
  0.3227236  0.36713783 0.39722292 0.69709733]
 [0.42624859 0.74245099 0.80039869 0.20568091 0.33605359 0.65143836
  0.04548213 0.67594546 0.73997998 0.21538934]
 [0.59400562 0.5087872  0.98125179 0.1860663  0.40471011 0.70064678
  0.30558854 0.47264593 0.1342379  0.06057423]
 [0.16336195 0.97458856 0.4940569  0.530093   0.86990744 0.87946373
  0.94159551 0.13452103 0.16071032 0.53554487]
 [0.42105715 0.5820659  0.13485098 0.09422756 0.54539671 0.4369463
  0.52890064 0.59921847 0.57290004 0.98353689]
 [0.6794989  0.81563642 0.79698577 0.98496818 0.10218489 0.41920156
  0.40169105 0.49413203 0.61264969 0.56844549]
 [0.39100078 0.45656349 0.30903962 0.8984735  0.58845716 0.95838855
  0.05405763 0.90574842 0.67764076 0.61170329]
 [0.59472776 0.27139518 0.59589619 0.83532255 0.89829972 0.2579772
  0.24910008 0.05107007 0.55675815 0.63769986]
 [0.35964963 0.67722458 0.82121801 0.3702437  0.40396125 0.22575133
  0.82978753 0

In [33]:
# Create a random vector of size 30 and find the mean value

e = np.random.random((30))
print(e.mean())


0.45341154925369026


In [42]:
# Create a 2d array with 1 on the border and 0 inside
f = np.ones((3,10))
print(f)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [43]:
f[1:-1,1:-1]=0
print(f)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [56]:
# What is the result of the following expression? (★☆☆)

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [68]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
g = np.diag(1+np.arange(4),-1)
print(g)
# print(g)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [92]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
h = np.zeros((8,8),dtype=int)
h[1::2,::2] = 1
h[::2,1::2] = 1
print(h)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [96]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
arr = np.random.random(((6,7,8)))
print(np.unravel_index(100,arr.shape))

(1, 5, 4)


In [105]:
# Create a checkerboard 8x8 matrix using the tile function 
np.tile((0,1),32).reshape(8,8)
# Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
# print(Z)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [107]:
# Normalize a 5x5 random matrix
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)


[[0.0406288  0.         0.76864171 0.23909015 0.30786166]
 [0.34864834 0.6801808  0.46669472 0.94738526 0.56352092]
 [0.32559204 0.13293881 0.21497641 0.95232418 0.74921802]
 [0.37348016 0.03695748 1.         0.14062442 0.45624041]
 [0.41783571 0.94352084 0.82928543 0.91591847 0.48246174]]


In [112]:
# Create a custom dtype that describes a color as four unisgned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

In [113]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [121]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [135]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.

j = np.arange(0,10)
j[(j>3) &(j<8)] *= -1
# if((j[0:len(j)]>3) & (j[0:len(j)]<8))
#     j = j*-1
    
print(j)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [159]:
# What is the output of the following script? (★☆☆)

# Author: Jake VanderPlas

# print(sum(range(5),-1))
# from numpy import *
# print(sum(range(5),-1))

In [209]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
import numpy as np
data = linspac-e(0, 1, 12, endpoint=False)[1:-1]
print(data)

# Z = np.arange(10)
# %time print(np.add.reduce(Z))
# %time print(np.sum(Z))

[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]
